version: '3.4'
services:
  intranet-zeo:
    image: docker-prod.affinitic.be/ploneintranet:latest
    user: plone
    volumes:
      - ./data:/plone/var
    working_dir: /plone
    command: /plone/bin/zeo fg
  intranet-solr:
    image: docker-prod.affinitic.be/ploneintranet:latest
    user: plone
    working_dir: /plone
    command: /plone/bin/solr-instance fg
  intranet-redis:
    image: redis
  intranet-celery:
    image: docker-prod.affinitic.be/ploneintranet:latest
    user: plone
    working_dir: /plone
    command: /plone/bin/celery -A ploneintranet.async.celerytasks worker --broker=redis://intranet-redis:6379/0
    depends_on:
      - intranet-redis
    environment:
      - BROKER_URL=redis://intranet-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://intranet-redis:6379/0
  intranet-flower:
    image: docker-prod.affinitic.be/ploneintranet:latest
    user: plone
    working_dir: /plone
    command: /plone/bin/celery -A ploneintranet.async.celerytasks flower --broker=redis://intranet-redis:6379/0
    depends_on:
      - intranet-celery
    environment:
      - BROKER_URL=redis://intranet-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://intranet-redis:6379/0
  intranet-instance1:
    image: docker-prod.affinitic.be/ploneintranet:latest
    user: plone
    ports:
      - '15080:8080'
    volumes:
      - ./data:/plone/var
    working_dir: /plone
    command: /plone/bin/instance fg
    depends_on:
      - intranet-celery
      - intranet-flower
      - intranet-solr
    environment:
      - BROKER_URL=redis://intranet-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://intranet-redis:6379/0
